# General settings
name: 'dev' # Warning: 'debug' and 'test' are reserved name that have a special behavior

parent_dir: '.'

wandb: 'online'             # online | offline | disabled
wandb_name: 'mass_spec_exp'
gpus: 1                     # Multi-gpu is not implemented on this branch

decoder: null # path to pretrained decoder
encoder: null # path to pretrained encoder

resume: null
test_only: null
load_weights: null

encoder_finetune_strategy: null  # null | freeze | ft-unfold | freeze-unfold | freeze-transformer | ft-transformer
decoder_finetune_strategy: null  # null | freeze | ft-input | freeze-input | ft-transformer | freeze-transformer | ft-output 

check_val_every_n_epochs: 1
sample_every_val: 1000
val_samples_to_generate: 100
test_samples_to_generate: 100
log_every_steps: 50

evaluate_all_checkpoints: False
checkpoint_strategy: 'last'

# Scaffold-constrained generation (optional)
scaffold_smiles: null           # SMILES string of scaffold substructure, e.g., "c1ccccc1"
target_formula: null            # Target molecular formula, e.g., "C10H12N2O"
attachment_indices: null        # Comma-separated attachment point indices, e.g., "2,5"
enforce_scaffold: False         # If True, enforce scaffold presence in generated molecules
use_rerank: False               # If True, rerank candidates by spectrum similarity